# 02 — Baseline Attribution Graphs (base model, v2 dataset)

Runs attribution graph generation on **base Gemma-2-2B** (no fine-tuning)
over the **v2 factorial prompt set** (`prompts_triangle_v2.jsonl`, ~300 prompts:
family × tail design with geometry + numeric families). Computes structural
statistics for each prompt and saves them to `results/statistics/stats_base_v2.json`.

The v1 pilot file (`stats_base.json`) is left untouched.

**Run as a script** to avoid kernel timeouts:
```bash
jupyter nbconvert --to script 02_baseline_attribution.ipynb
python 02_baseline_attribution.py
```

Saves incrementally (every prompt) so a restart resumes from the last checkpoint.

**Prerequisites:** `01_dataset_generation.ipynb` must have been run (v2 cell).

## 0 — Environment Setup

In [1]:
import os
import sys
from pathlib import Path

# Must be set BEFORE torch is imported anywhere to take effect.
# Prevents CUDA allocator fragmentation on long sequential attribution loops
# (without this, OOMs appear around prompt 12 even when VRAM is nominally free).
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

IN_RUNPOD = os.environ.get("RUNPOD_POD_ID") is not None

def _find_repo_root():
    start = Path.cwd().resolve()
    for directory in [start, *start.parents]:
        if (directory / "circuit_tracer" / "__init__.py").is_file():
            return directory
    workspace = Path("/workspace")
    if workspace.is_dir():
        for child in workspace.iterdir():
            if child.is_dir() and (child / "circuit_tracer" / "__init__.py").is_file():
                return child
    repo_override = os.environ.get("CT_REPO_DIR")
    if repo_override:
        override_path = Path(repo_override).expanduser().resolve()
        if (override_path / "circuit_tracer" / "__init__.py").is_file():
            return override_path
    return None

_root = _find_repo_root()
if _root is not None:
    if str(_root) not in sys.path:
        sys.path.insert(0, str(_root))
    _my_work = _root / "my_work"
    if str(_my_work) not in sys.path:
        sys.path.insert(0, str(_my_work))
    print(f"Repo root: {_root}")
else:
    print("WARNING: could not locate circuit_tracer repo.")

try:
    from dotenv import load_dotenv
    if _root is not None and (_root / ".env").is_file():
        load_dotenv(_root / ".env")
        print("Loaded .env")
except ImportError:
    pass

# Persistent HF cache for RunPod
if IN_RUNPOD:
    persistent_root = Path(os.environ.get("RUNPOD_PERSISTENT_ROOT", "/workspace")).resolve()
    hf_home = persistent_root / "hf"
    for key, path in {
        "HF_HOME": hf_home,
        "HUGGINGFACE_HUB_CACHE": hf_home / "hub",
        "TRANSFORMERS_CACHE": hf_home / "transformers",
    }.items():
        path.mkdir(parents=True, exist_ok=True)
        os.environ[key] = str(path)
    print(f"RunPod cache: {hf_home}")

MY_WORK = _my_work if _root else Path(".").resolve()
print(f"MY_WORK: {MY_WORK}")

Repo root: /workspace/thesis_circuit_breaker
RunPod cache: /workspace/hf
MY_WORK: /workspace/thesis_circuit_breaker/my_work

## 1 — Imports & constants

In [2]:
import json
import time
import traceback

import torch
import numpy as np

# ── Plan constants (never change) ──────────────────────────────────────────────
MODEL_NAME      = "google/gemma-2-2b"
TRANSCODER_NAME = "gemma"
TOKEN_TRUE      = " True"
TOKEN_FALSE     = " False"
VOCAB_ID_TRUE   = 5569
VOCAB_ID_FALSE  = 7662

ATTR_KWARGS = dict(
    batch_size=256,
    max_feature_nodes=8192,
    offload="disk",
    verbose=False,
)

PHASE = "base"

# ── Paths ──────────────────────────────────────────────────────────────────────
# v2: uses supervisor-aligned factorial prompt set and separate stats file.
# Pilot stats (stats_base.json from v1 run) are left untouched.
DATASET_FILE   = MY_WORK / "data" / "prompts_triangle_v2.jsonl"
GRAPHS_DIR     = MY_WORK / "results" / "graphs_base_v2"
STATS_FILE     = MY_WORK / "results" / "statistics" / "stats_base_v2.json"
# Second-pod shard from `02b_baseline_attribution_pod2_from160.ipynb` (writes here).
# §5 resume unions successful `prompt_id`s from both so this pod skips work
# already finished on the shard (no duplicate attribution).
SHARD_STATS_FILE = MY_WORK / "results" / "statistics" / "stats_base_v2_from160.json"

GRAPHS_DIR.mkdir(parents=True, exist_ok=True)
STATS_FILE.parent.mkdir(parents=True, exist_ok=True)

print(f"Dataset file  : {DATASET_FILE}")
print(f"Graphs dir    : {GRAPHS_DIR}")
print(f"Stats output  : {STATS_FILE}")
print(f"Shard (resume): {SHARD_STATS_FILE}  (exists={SHARD_STATS_FILE.exists()})")
print(f"CUDA available: {torch.cuda.is_available()}")

# ReplacementModel.from_pretrained expects a torch.device, not a plain string.
device_str = "cuda" if torch.cuda.is_available() else "cpu"
device = torch.device(device_str)
print(f"Device        : {device}")

Dataset file  : /workspace/thesis_circuit_breaker/my_work/data/prompts_triangle_v2.jsonl
Graphs dir    : /workspace/thesis_circuit_breaker/my_work/results/graphs_base_v2
Stats output  : /workspace/thesis_circuit_breaker/my_work/results/statistics/stats_base_v2.json
Shard (resume): /workspace/thesis_circuit_breaker/my_work/results/statistics/stats_base_v2_from160.json  (exists=True)
CUDA available: True
Device        : cuda

## 2 — Load full dataset (300 prompts)

In [3]:
analysis_prompts = []
with open(DATASET_FILE, "r", encoding="utf-8") as f:
    for line in f:
        analysis_prompts.append(json.loads(line.strip()))

binary = [p for p in analysis_prompts if p.get("task_type", "binary") == "binary"]
numeric = [p for p in analysis_prompts if p.get("task_type", "binary") == "numeric"]

print(f"Loaded {len(analysis_prompts)} prompts from full dataset")
print(f"  Binary : {len(binary)}")
print(f"    True : {sum(1 for p in binary if p['label'])}")
print(f"    False: {sum(1 for p in binary if not p['label'])}")
print(f"  Numeric: {len(numeric)}")
if numeric:
    print(f"    Targets: {sorted(set(p['label_token'] for p in numeric))}")
else:
    print("    Targets: []")

Loaded 300 prompts from full dataset
  Binary : 270
    True : 135
    False: 135
  Numeric: 30
    Targets: ['1', '2', '3', '5', '6', '7', '8', '9']

## 3 — Load model

In [4]:
from circuit_tracer import ReplacementModel

model = ReplacementModel.from_pretrained(
    MODEL_NAME,
    TRANSCODER_NAME,
    dtype=torch.bfloat16,
    backend="transformerlens",
    device=device,
    lazy_encoder=True,
    lazy_decoder=True,
)
tokenizer = model.tokenizer

# Verify token IDs match constants
id_true  = tokenizer.encode(TOKEN_TRUE,  add_special_tokens=False)[-1]
id_false = tokenizer.encode(TOKEN_FALSE, add_special_tokens=False)[-1]
assert id_true  == VOCAB_ID_TRUE,  f"TOKEN_TRUE id mismatch: {id_true} != {VOCAB_ID_TRUE}"
assert id_false == VOCAB_ID_FALSE, f"TOKEN_FALSE id mismatch: {id_false} != {VOCAB_ID_FALSE}"
print(f"Token IDs verified: True={id_true}, False={id_false}")

/workspace/venvs/ct/lib/python3.11/site-packages/transformers/utils/hub.py:110: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(

Fetching 26 files:   0%|          | 0/26 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Loaded pretrained model google/gemma-2-2b into HookedTransformer
Token IDs verified: True=5569, False=7662

## 4 — First-token accuracy check (pre-attribution)

Quick sanity check: does the base model's top-1 token match the expected next token?
For binary prompts this is True/False accuracy; for numeric prompts this is exact token match.

In [9]:
overall_correct = 0

binary_correct = 0
binary_total = 0
correct_true = 0
total_true = 0
correct_false = 0
total_false = 0

numeric_correct = 0
numeric_total = 0

# Keep per-prompt predictions in memory for downstream inspection/export.
first_token_predictions = []

progress_every = 10
acc_t0 = time.time()

with torch.inference_mode():
    for idx, entry in enumerate(analysis_prompts, start=1):
        # ReplacementModel (TransformerLens backend) does not expose .model;
        # use the no-op intervention path to get baseline logits.
        logits, _ = model.feature_intervention(entry["prompt"], [])
        last_logit = logits.squeeze(0)[-1, :]
        pred_id = int(last_logit.argmax().item())
        pred_token = tokenizer.decode([pred_id])

        task_type = entry.get("task_type", "binary")
        if task_type == "binary":
            label_id = VOCAB_ID_TRUE if entry["label"] else VOCAB_ID_FALSE
            expected_response = TOKEN_TRUE if entry["label"] else TOKEN_FALSE
            binary_total += 1
            is_correct = (pred_id == label_id)
            if is_correct:
                binary_correct += 1
                overall_correct += 1
            if entry["label"]:
                total_true += 1
                if pred_id == VOCAB_ID_TRUE:
                    correct_true += 1
            else:
                total_false += 1
                if pred_id == VOCAB_ID_FALSE:
                    correct_false += 1
        else:
            # Robust handling: if label_token is multi-token (e.g. ' 9'),
            # fallback to stripped variant (e.g. '9') when single-token.
            raw_label = entry["label_token"]
            label_ids = tokenizer.encode(raw_label, add_special_tokens=False)
            expected_response = raw_label
            if len(label_ids) != 1:
                alt = raw_label.lstrip()
                alt_ids = tokenizer.encode(alt, add_special_tokens=False)
                if len(alt_ids) == 1:
                    label_ids = alt_ids
                    expected_response = alt
                else:
                    raise ValueError(
                        f"Numeric label token must resolve to a single token, got {raw_label!r} -> {label_ids}, alt {alt!r} -> {alt_ids}"
                    )
            label_id = int(label_ids[0])
            numeric_total += 1
            is_correct = (pred_id == label_id)
            if is_correct:
                numeric_correct += 1
                overall_correct += 1

        first_token_predictions.append({
            "prompt_id": entry["prompt_id"],
            "task_type": task_type,
            "expected_response": expected_response,
            "argmax_response": pred_token,
            "expected_token_id": label_id,
            "argmax_token_id": pred_id,
            "is_correct": is_correct,
        })

        if idx % progress_every == 0 or idx == len(analysis_prompts):
            elapsed = max(time.time() - acc_t0, 1e-9)
            speed = idx / elapsed
            eta = (len(analysis_prompts) - idx) / speed if speed > 0 else float("inf")
            print(
                f"[accuracy progress] {idx}/{len(analysis_prompts)} "
                f"({idx/len(analysis_prompts):.0%}) | "
                f"running overall={overall_correct/max(idx,1):.1%} | "
                f"{speed:.2f} prompts/s | ETA {eta:.1f}s"
            )

n = len(analysis_prompts)
print("Base model first-token accuracy on full dataset:")
print(f"  Overall : {overall_correct}/{n} = {overall_correct/n:.1%}")
if binary_total:
    print(f"  Binary  : {binary_correct}/{binary_total} = {binary_correct/binary_total:.1%}")
    print(f"    True  : {correct_true}/{total_true} = {correct_true/max(total_true,1):.1%}")
    print(f"    False : {correct_false}/{total_false} = {correct_false/max(total_false,1):.1%}")
if numeric_total:
    print(f"  Numeric : {numeric_correct}/{numeric_total} = {numeric_correct/numeric_total:.1%}")

if overall_correct / n > 0.80:
    print()
    print("NOTE: First-token accuracy >80%. Interpretability gains may appear smaller.")

print()
print(f"Stored per-prompt predictions in memory: first_token_predictions (n={len(first_token_predictions)})")
print("Preview (first 5):")
for row in first_token_predictions[:5]:
    print(
        f"  {row['prompt_id']}: expected={row['expected_response']!r} "
        f"argmax={row['argmax_response']!r} correct={row['is_correct']}"
    )

[accuracy progress] 10/300 (3%) | running overall=10.0% | 0.46 prompts/s | ETA 632.6s
[accuracy progress] 20/300 (7%) | running overall=25.0% | 0.57 prompts/s | ETA 488.0s
[accuracy progress] 30/300 (10%) | running overall=20.0% | 0.63 prompts/s | ETA 430.9s
[accuracy progress] 40/300 (13%) | running overall=20.0% | 0.65 prompts/s | ETA 397.4s
[accuracy progress] 50/300 (17%) | running overall=18.0% | 0.67 prompts/s | ETA 370.8s
[accuracy progress] 60/300 (20%) | running overall=18.3% | 0.69 prompts/s | ETA 348.4s
[accuracy progress] 70/300 (23%) | running overall=15.7% | 0.70 prompts/s | ETA 328.4s
[accuracy progress] 80/300 (27%) | running overall=17.5% | 0.71 prompts/s | ETA 310.5s
[accuracy progress] 90/300 (30%) | running overall=20.0% | 0.71 prompts/s | ETA 294.7s
[accuracy progress] 100/300 (33%) | running overall=20.0% | 0.72 prompts/s | ETA 278.5s
[accuracy progress] 110/300 (37%) | running overall=20.0% | 0.72 prompts/s | ETA 262.7s
[accuracy progress] 120/300 (40%) | running overall=19.2% | 0.73 prompts/s | ETA 247.5s
[accuracy progress] 130/300 (43%) | running overall=18.5% | 0.73 prompts/s | ETA 232.7s
[accuracy progress] 140/300 (47%) | running overall=17.9% | 0.73 prompts/s | ETA 218.4s
[accuracy progress] 150/300 (50%) | running overall=18.0% | 0.73 prompts/s | ETA 204.3s
[accuracy progress] 160/300 (53%) | running overall=18.1% | 0.74 prompts/s | ETA 190.1s
[accuracy progress] 170/300 (57%) | running overall=17.1% | 0.74 prompts/s | ETA 175.9s
[accuracy progress] 180/300 (60%) | running overall=17.8% | 0.74 prompts/s | ETA 161.9s
[accuracy progress] 190/300 (63%) | running overall=17.4% | 0.74 prompts/s | ETA 148.4s
[accuracy progress] 200/300 (67%) | running overall=17.0% | 0.74 prompts/s | ETA 134.6s
[accuracy progress] 210/300 (70%) | running overall=16.2% | 0.74 prompts/s | ETA 121.0s
[accuracy progress] 220/300 (73%) | running overall=16.4% | 0.74 prompts/s | ETA 107.5s
[accuracy progress] 230/300 (77%) | running overall=15.7% | 0.74 prompts/s | ETA 94.0s
[accuracy progress] 240/300 (80%) | running overall=16.2% | 0.75 prompts/s | ETA 80.5s
[accuracy progress] 250/300 (83%) | running overall=16.0% | 0.75 prompts/s | ETA 67.0s
[accuracy progress] 260/300 (87%) | running overall=16.2% | 0.75 prompts/s | ETA 53.5s
[accuracy progress] 270/300 (90%) | running overall=16.7% | 0.75 prompts/s | ETA 40.1s
[accuracy progress] 280/300 (93%) | running overall=17.1% | 0.75 prompts/s | ETA 26.7s
[accuracy progress] 290/300 (97%) | running overall=16.9% | 0.75 prompts/s | ETA 13.4s
[accuracy progress] 300/300 (100%) | running overall=16.7% | 0.75 prompts/s | ETA 0.0s
Base model first-token accuracy on full dataset:
  Overall : 50/300 = 16.7%
  Binary  : 50/270 = 18.5%
    True  : 23/135 = 17.0%
    False : 27/135 = 20.0%
  Numeric : 0/30 = 0.0%

Stored per-prompt predictions in memory: first_token_predictions (n=300)
Preview (first 5):
  tri_v2_001: expected=' False' argmax=' False' correct=True
  tri_v2_002: expected=' True' argmax=' Yes' correct=False
  tri_v2_003: expected=' False' argmax='\n\n' correct=False
  tri_v2_004: expected=' True' argmax='\n\n' correct=False
  tri_v2_005: expected=' False' argmax='\n\n' correct=False

This is interesting, and may cause some trouble. The " 9" is tokenized to two, so we try to get the "9" token prediction. For the numeric, it appears that the most likely first token was always " " whitespace.

In [10]:
import pandas as pd

_ft_csv = MY_WORK / "results" / "first_token" / "base_v2_predictions.csv"
_ft_csv.parent.mkdir(parents=True, exist_ok=True)
pd.DataFrame(first_token_predictions).to_csv(_ft_csv, index=False)
print(f"First-token rows saved → {_ft_csv}")

First-token rows saved → /workspace/thesis_circuit_breaker/my_work/results/first_token/base_v2_predictions.csv

## 4b — First-token probability tables (monitoring)

Same machinery as **`04c`** §3b, on the **base** **`ReplacementModel`**: two passes over **`analysis_prompts`** — binary rows collect softmax mass on **`VOCAB_ID_TRUE`** / **`VOCAB_ID_FALSE`** at the last prompt position; numeric rows collect **`prob_digit_0`** … **`prob_digit_9`**. Results: **`df_binary_token_probs`** and **`df_numeric_digit_probs`**; CSVs next to **`base_v2_predictions.csv`**.

In [5]:
import pandas as pd
import torch.nn.functional as F
from IPython.display import display

PROB_MONITOR_EVERY = max(5, max(1, len(analysis_prompts)) // 20)


def _last_vocab_probs(prompt: str) -> torch.Tensor:
    logits, _ = model.feature_intervention(prompt, [])
    last = logits.squeeze(0)[-1, :].float()
    return F.softmax(last, dim=-1)


def _resolve_digit_vocab_id(d: int) -> int:
    """Single-token vocab id Gemma assigns to digit continuation (plain or spaced)."""
    ch = str(int(d))
    for variant in (ch, f" {ch}"):
        tids = tokenizer.encode(variant, add_special_tokens=False)
        if len(tids) == 1:
            return int(tids[0])
    raise ValueError(f"Digit {d!r} must map to a single token; tried {ch!r} and {(' ' + ch)!r}")


DIGIT_IDS = [_resolve_digit_vocab_id(d) for d in range(10)]
print(f"Digit vocab ids [0..9]: {DIGIT_IDS}")

binary_list = [p for p in analysis_prompts if p.get("task_type", "binary") == "binary"]
numeric_list = [p for p in analysis_prompts if p.get("task_type", "binary") == "numeric"]

# --- Pass 1: binary ---
t0 = time.time()
binary_rows = []
for i, entry in enumerate(binary_list, 1):
    probs = _last_vocab_probs(entry["prompt"])
    pt = float(probs[VOCAB_ID_TRUE].item())
    pf = float(probs[VOCAB_ID_FALSE].item())
    binary_rows.append(
        {
            "prompt_id": entry["prompt_id"],
            "family": entry.get("family"),
            "tail": entry.get("tail"),
            "label": entry.get("label"),
            "task_type": entry.get("task_type", "binary"),
            "prob_true": pt,
            "prob_false": pf,
            "prob_mass_tf": pt + pf,
        }
    )
    if PROB_MONITOR_EVERY and (i % PROB_MONITOR_EVERY == 0 or i == len(binary_list)):
        dt = max(time.time() - t0, 1e-6)
        print(
            f"  binary {i}/{len(binary_list)}  "
            f"{i/dt:.2f}/s  ETA {(len(binary_list) - i) / max(i / dt, 1e-6):.1f}s"
        )

t1 = time.time()
df_binary_token_probs = pd.DataFrame(binary_rows)
print(f"df_binary_token_probs rows={len(df_binary_token_probs)}  wall={t1-t0:.1f}s")

# --- Pass 2: numeric digit masses ---
numeric_rows = []
t0 = time.time()
for i, entry in enumerate(numeric_list, 1):
    probs = _last_vocab_probs(entry["prompt"])
    row = {
        "prompt_id": entry["prompt_id"],
        "family": entry.get("family"),
        "tail": entry.get("tail"),
        "label": entry.get("label"),
        "label_token": entry.get("label_token"),
        "task_type": entry.get("task_type"),
    }
    mass = 0.0
    for d in range(10):
        p = float(probs[DIGIT_IDS[d]].item())
        row[f"prob_digit_{d}"] = p
        mass += p
    row["prob_mass_digits"] = mass
    numeric_rows.append(row)
    if PROB_MONITOR_EVERY and (i % PROB_MONITOR_EVERY == 0 or i == len(numeric_list)):
        dt = max(time.time() - t0, 1e-6)
        print(
            f"  numeric {i}/{len(numeric_list)}  "
            f"{i/dt:.2f}/s  ETA {(len(numeric_list) - i) / max(i / dt, 1e-6):.1f}s"
        )

t1 = time.time()
df_numeric_digit_probs = pd.DataFrame(numeric_rows)
print(f"df_numeric_digit_probs rows={len(df_numeric_digit_probs)}  wall={t1-t0:.1f}s")

display(df_binary_token_probs.head(3))
display(df_numeric_digit_probs.head(3))

FIRST_TOKEN_DIR = MY_WORK / "results" / "first_token"
FIRST_TOKEN_DIR.mkdir(parents=True, exist_ok=True)
stem = f"{PHASE}_v2"
path_bin = FIRST_TOKEN_DIR / f"{stem}_binary_token_probs.csv"
path_num = FIRST_TOKEN_DIR / f"{stem}_numeric_digit_probs.csv"
df_binary_token_probs.to_csv(path_bin, index=False)
df_numeric_digit_probs.to_csv(path_num, index=False)
print(f"Wrote {path_bin}")
print(f"Wrote {path_num}")

Digit vocab ids [0..9]: [235276, 235274, 235284, 235304, 235310, 235308, 235318, 235324, 235321, 235315]
  binary 15/270  0.52/s  ETA 486.1s
  binary 30/270  0.62/s  ETA 388.3s
  binary 45/270  0.66/s  ETA 342.4s
  binary 60/270  0.68/s  ETA 310.1s
  binary 75/270  0.69/s  ETA 282.5s
  binary 90/270  0.70/s  ETA 257.1s
  binary 105/270  0.71/s  ETA 233.5s
  binary 120/270  0.71/s  ETA 210.3s
  binary 135/270  0.72/s  ETA 187.8s
  binary 150/270  0.72/s  ETA 165.9s
  binary 165/270  0.73/s  ETA 144.7s
  binary 180/270  0.73/s  ETA 123.5s
  binary 195/270  0.73/s  ETA 102.5s
  binary 210/270  0.73/s  ETA 81.8s
  binary 225/270  0.74/s  ETA 61.2s
  binary 240/270  0.74/s  ETA 40.8s
  binary 255/270  0.74/s  ETA 20.4s
  binary 270/270  0.74/s  ETA 0.0s
df_binary_token_probs rows=270  wall=366.2s
  numeric 15/30  0.75/s  ETA 20.1s
  numeric 30/30  0.75/s  ETA 0.0s
df_numeric_digit_probs rows=30  wall=39.9s

,prompt_id,family,tail,label,task_type,prob_true,prob_false,prob_mass_tf
0,tri_v2_001,numeric_validity,answer_colon,False,binary,0.027665,0.123986,0.151651
1,tri_v2_002,numeric_validity,answer_colon,True,binary,0.111551,0.028205,0.139756
2,tri_v2_003,numeric_validity,true_or_false,False,binary,0.004878,0.000960,0.005838

,prompt_id,family,tail,label,label_token,task_type,prob_digit_0,prob_digit_1,prob_digit_2,prob_digit_3,prob_digit_4,prob_digit_5,prob_digit_6,prob_digit_7,prob_digit_8,prob_digit_9,prob_mass_digits
0,tri_v2_009,numeric_open,answer_colon,6,6,numeric,0.000192,0.001419,0.001253,0.000670,0.000592,0.000359,0.000522,0.000192,0.000132,0.000091,0.005422
1,tri_v2_010,numeric_open,answer_colon,2,2,numeric,0.000166,0.001788,0.001788,0.000745,0.000658,0.000352,0.000274,0.000188,0.000114,0.000089,0.006163
2,tri_v2_024,numeric_open,answer_colon,3,3,numeric,0.000130,0.001579,0.001579,0.000845,0.000746,0.000352,0.000311,0.000214,0.000130,0.000101,0.005988

Wrote /workspace/thesis_circuit_breaker/my_work/results/first_token/base_v2_binary_token_probs.csv
Wrote /workspace/thesis_circuit_breaker/my_work/results/first_token/base_v2_numeric_digit_probs.csv

In [11]:
pd.DataFrame(first_token_predictions)

,prompt_id,task_type,expected_response,argmax_response,expected_token_id,argmax_token_id,is_correct
0,tri_v2_001,binary,False,False,7662,7662,True
1,tri_v2_002,binary,True,Yes,5569,6287,False
2,tri_v2_003,binary,False,\n\n,7662,109,False
3,tri_v2_004,binary,True,\n\n,5569,109,False
4,tri_v2_005,binary,False,\n\n,7662,109,False
...,...,...,...,...,...,...,...
295,tri_v2_296,binary,False,False,7662,7662,True
296,tri_v2_297,binary,False,no,7662,793,False
297,tri_v2_298,binary,True,:,5569,235292,False
298,tri_v2_299,binary,True,,5569,235248,False
299,tri_v2_300,binary,False,no,7662,793,False

## 5 — Attribution + stats (coupled, storage-safe)

Runs attribution for each prompt and computes stats **immediately in one pass** —
graph objects are discarded after stats are extracted (no full graph persisted to disk).

**Artifact policy (configured by `N_FULL_GRAPH`):**
- First `N_FULL_GRAPH` prompts (dataset order): save `.pt` + frontend JSON for inspection/figures.
- All prompts: compute and append stats to `stats_base_v2.json` only.
- Remaining prompts: stats-only, no large graph files written.

**Resume:** successfully attributed `prompt_id`s in **`stats_base_v2.json`** *or* (if present) **`stats_base_v2_from160.json`** (from **`02b`** on a second pod) are skipped. New rows append only to **`stats_base_v2.json`**. Merge the two JSON arrays offline if you want one file for analysis.

In [5]:
import sys, importlib
sys.modules.pop("utils.graph_statistics", None)
import utils.graph_statistics as gs
importlib.reload(gs)

from circuit_tracer import attribute
from circuit_tracer.utils import create_graph_files
from utils.graph_statistics import compute_statistics, load_statistics, append_statistic

# Number of prompts for which full graph artifacts (.pt + JSON) are kept.
# All others get stats-only extraction (no large disk writes).
N_FULL_GRAPH = 10

def _resolve_attr_targets(entry: dict) -> list[str]:
    task_type = entry.get("task_type", "binary")
    if task_type == "binary":
        return [TOKEN_TRUE, TOKEN_FALSE]
    raw_label = entry["label_token"]
    ids_raw = tokenizer.encode(raw_label, add_special_tokens=False)
    if len(ids_raw) == 1:
        return [raw_label]
    alt = raw_label.lstrip()
    ids_alt = tokenizer.encode(alt, add_special_tokens=False)
    if len(ids_alt) == 1:
        return [alt]
    raise ValueError(
        f"Numeric attribution target must be single-token, "
        f"got {raw_label!r}->{ids_raw}, alt {alt!r}->{ids_alt}"
    )

def _graph_pt_path(prompt_id: str) -> Path:
    return GRAPHS_DIR / prompt_id / f"{prompt_id}.pt"

print(f"N_FULL_GRAPH     : {N_FULL_GRAPH}  (full artifacts for first {N_FULL_GRAPH} prompts)")
print(f"Module file      : {gs.__file__}")
print(f"Robust load_stat : {'if not raw.strip():' in Path(gs.__file__).read_text()}")

N_FULL_GRAPH     : 10  (full artifacts for first 10 prompts)
Module file      : /workspace/thesis_circuit_breaker/my_work/utils/graph_statistics.py
Robust load_stat : True

In [6]:
# ── Resume: skip successfully-attributed prompts (main + optional 02b shard) ─
# Prompts with attribution_succeeded False in the MAIN file are retried here.
# Rows still append only to STATS_FILE (shard is read-only for done_ids).

def _done_prompt_ids(path) -> set[str]:
    return {
        e["prompt_id"]
        for e in load_statistics(path)
        if e.get("prompt_id") is not None and e.get("attribution_succeeded")
    }

existing_stats = load_statistics(STATS_FILE)
done_main = _done_prompt_ids(STATS_FILE)
done_shard: set[str] = set()
if SHARD_STATS_FILE.exists():
    done_shard = _done_prompt_ids(SHARD_STATS_FILE)

done_ids = done_main | done_shard
n_failed_prev = sum(1 for e in existing_stats if not e.get("attribution_succeeded"))

print(f"Succeeded in {STATS_FILE.name}     : {len(done_main)}")
if SHARD_STATS_FILE.exists():
    print(f"Succeeded in {SHARD_STATS_FILE.name}: {len(done_shard)}")
else:
    print(f"Shard missing (no union)           : {SHARD_STATS_FILE}")
print(f"Union skip set                     : {len(done_ids)}")
print(f"Previously failed (main file)    : {n_failed_prev} (retried if still in remaining)")

remaining = [p for p in analysis_prompts if p["prompt_id"] not in done_ids]
print(f"Remaining    : {len(remaining)} prompts")

# Full artifacts are saved only for the first N_FULL_GRAPH prompts (by dataset order).
# Determine which prompt IDs qualify, regardless of what is already done.
full_artifact_ids = {p["prompt_id"] for p in analysis_prompts[:N_FULL_GRAPH]}
print(f"Full-artifact set: {sorted(full_artifact_ids)}")

Succeeded in stats_base_v2.json     : 52
Succeeded in stats_base_v2_from160.json: 141
Union skip set                     : 193
Previously failed (main file)    : 0 (retried if still in remaining)
Remaining    : 107 prompts
Full-artifact set: ['tri_v2_001', 'tri_v2_002', 'tri_v2_003', 'tri_v2_004', 'tri_v2_005', 'tri_v2_006', 'tri_v2_007', 'tri_v2_008', 'tri_v2_009', 'tri_v2_010']

In [7]:
import gc

# ── Coupled attribution + stats loop ──────────────────────────────────────────
t0 = time.time()
n_success = 0
n_fail = 0
progress_every = 5

for i, entry in enumerate(remaining, start=1):
    pid = entry["prompt_id"]
    task_type = entry.get("task_type", "binary")
    save_full = pid in full_artifact_ids
    print(f"[{i}/{len(remaining)}] {pid} ({task_type})"
          f"{' [full artifact]' if save_full else ''} ...", end=" ", flush=True)

    try:
        graph = attribute(
            prompt=entry["prompt"],
            model=model,
            attribution_targets=_resolve_attr_targets(entry),
            **ATTR_KWARGS,
        )

        # Compute stats immediately — before any optional disk I/O.
        stat = compute_statistics(graph, entry, phase=PHASE)
        append_statistic(stat, STATS_FILE)
        n_success += 1

        # Full artifact save for inspection subset only.
        if save_full:
            graph_out = GRAPHS_DIR / pid
            graph_out.mkdir(parents=True, exist_ok=True)
            graph.to_pt(str(_graph_pt_path(pid)))
            create_graph_files(graph, slug=pid, output_path=str(graph_out))

        # Discard large graph tensor, then aggressively free CUDA memory to
        # prevent allocator fragmentation across 300 sequential attribution calls.
        del graph
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.synchronize()
            torch.cuda.empty_cache()
            torch.cuda.ipc_collect()

        density = stat.get("edge_density")
        t20 = stat.get("topk20") or {}
        ls = stat.get("layer_stats") or {}
        print(
            f"OK  n_active={stat.get('n_active_features')}"
            + (f"  density={density:.4f}" if density is not None else "  density=N/A")
            + (f"  topk20={t20.get('score_total'):.3f}" if t20.get('score_total') is not None else "")
            + (f"  ent={ls.get('entropy_bits'):.2f}b" if ls.get('entropy_bits') is not None else "")
            + (" [saved .pt+JSON]" if save_full else "")
        )

    except Exception as exc:
        # Failed rows are NOT added to done_ids so resume will retry them.
        stat = {
            "prompt_id": pid,
            "phase": PHASE,
            "task_type": task_type,
            "family": entry.get("family"),
            "tail": entry.get("tail"),
            "label": entry["label"],
            "label_token": entry["label_token"],
            "template_id": entry.get("template_id"),
            "attribution_succeeded": False,
            "_error": str(exc),
        }
        append_statistic(stat, STATS_FILE)
        n_fail += 1
        print(f"FAIL {exc}")
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if i % progress_every == 0 or i == len(remaining):
        elapsed = max(time.time() - t0, 1e-9)
        speed = i / elapsed
        eta = (len(remaining) - i) / speed if speed > 0 else float("inf")
        print(
            f"[progress] {i}/{len(remaining)} ({i/len(remaining):.0%}) | "
            f"success={n_success/max(i,1):.1%} | "
            f"{speed:.3f} prompts/s | ETA {eta/60:.1f} min"
        )

print()
print(f"Done. Elapsed: {time.time() - t0:.0f}s")
print(f"  Successes : {n_success}")
print(f"  Failures  : {n_fail}")

[1/107] tri_v2_053 (numeric) ... OK  n_active=29720  density=0.1199  topk20=0.000  ent=4.20b
[2/107] tri_v2_054 (binary) ... OK  n_active=26004  density=0.1190  topk20=0.001  ent=4.24b
[3/107] tri_v2_055 (binary) ... OK  n_active=20086  density=0.1201  topk20=0.057  ent=4.26b
[4/107] tri_v2_056 (binary) ... OK  n_active=19559  density=0.1186  topk20=0.000  ent=4.27b
[5/107] tri_v2_057 (numeric) ... OK  n_active=28649  density=0.1168  topk20=0.000  ent=4.20b
[progress] 5/107 (5%) | success=100.0% | 0.012 prompts/s | ETA 138.7 min
[6/107] tri_v2_058 (binary) ... OK  n_active=18462  density=0.1278  topk20=0.001  ent=4.29b
[7/107] tri_v2_059 (binary) ... OK  n_active=31420  density=0.1110  topk20=0.001  ent=4.20b
[8/107] tri_v2_060 (binary) ... OK  n_active=32729  density=0.1125  topk20=0.001  ent=4.19b
[9/107] tri_v2_061 (binary) ... OK  n_active=16380  density=0.1237  topk20=0.001  ent=4.27b
[10/107] tri_v2_062 (binary) ... OK  n_active=18590  density=0.1089  topk20=0.017  ent=4.26b
[progress] 10/107 (9%) | success=100.0% | 0.012 prompts/s | ETA 130.9 min
[11/107] tri_v2_063 (binary) ... OK  n_active=21545  density=0.1234  topk20=0.001  ent=4.27b
[12/107] tri_v2_064 (binary) ... OK  n_active=20224  density=0.1186  topk20=0.000  ent=4.26b
[13/107] tri_v2_065 (binary) ... OK  n_active=15350  density=0.1239  topk20=0.023  ent=4.28b
[14/107] tri_v2_066 (numeric) ... OK  n_active=28797  density=0.1195  topk20=0.000  ent=4.21b
[15/107] tri_v2_067 (binary) ... OK  n_active=29305  density=0.1212  topk20=0.001  ent=4.24b
[progress] 15/107 (14%) | success=100.0% | 0.012 prompts/s | ETA 124.7 min
[16/107] tri_v2_068 (binary) ... OK  n_active=18665  density=0.1099  topk20=0.011  ent=4.26b
[17/107] tri_v2_069 (binary) ... OK  n_active=17808  density=0.1307  topk20=0.001  ent=4.29b
[18/107] tri_v2_070 (binary) ... OK  n_active=29843  density=0.1223  topk20=0.001  ent=4.24b
[19/107] tri_v2_071 (binary) ... OK  n_active=15551  density=0.1282  topk20=0.090  ent=4.28b
[20/107] tri_v2_072 (binary) ... OK  n_active=24269  density=0.1166  topk20=0.013  ent=4.21b
[progress] 20/107 (19%) | success=100.0% | 0.012 prompts/s | ETA 116.2 min
[21/107] tri_v2_073 (binary) ... OK  n_active=24861  density=0.1248  topk20=0.001  ent=4.24b
[22/107] tri_v2_074 (binary) ... OK  n_active=18635  density=0.1184  topk20=0.001  ent=4.29b
[23/107] tri_v2_075 (binary) ... OK  n_active=29113  density=0.1169  topk20=0.000  ent=4.25b
[24/107] tri_v2_076 (binary) ... OK  n_active=16469  density=0.1291  topk20=0.001  ent=4.27b
[25/107] tri_v2_077 (binary) ... OK  n_active=16325  density=0.1302  topk20=0.001  ent=4.28b
[progress] 25/107 (23%) | success=100.0% | 0.013 prompts/s | ETA 109.1 min
[26/107] tri_v2_078 (binary) ... OK  n_active=16532  density=0.1205  topk20=0.078  ent=4.29b
[27/107] tri_v2_079 (binary) ... OK  n_active=19281  density=0.1224  topk20=0.059  ent=4.26b
[28/107] tri_v2_080 (binary) ... OK  n_active=23220  density=0.1195  topk20=0.020  ent=4.22b
[29/107] tri_v2_081 (numeric) ... OK  n_active=30613  density=0.1150  topk20=0.000  ent=4.21b
[30/107] tri_v2_082 (binary) ... OK  n_active=20142  density=0.1252  topk20=0.001  ent=4.26b
[progress] 30/107 (28%) | success=100.0% | 0.013 prompts/s | ETA 100.2 min
[31/107] tri_v2_083 (binary) ... OK  n_active=17772  density=0.1284  topk20=0.081  ent=4.28b
[32/107] tri_v2_084 (binary) ... OK  n_active=32270  density=0.1121  topk20=0.002  ent=4.20b
[33/107] tri_v2_085 (binary) ... OK  n_active=17294  density=0.1244  topk20=0.077  ent=4.30b
[34/107] tri_v2_086 (binary) ... OK  n_active=24996  density=0.1242  topk20=0.001  ent=4.24b
[35/107] tri_v2_087 (binary) ... OK  n_active=21330  density=0.1220  topk20=0.049  ent=4.27b
[progress] 35/107 (33%) | success=100.0% | 0.013 prompts/s | ETA 92.8 min
[36/107] tri_v2_088 (numeric) ... OK  n_active=29217  density=0.1167  topk20=0.000  ent=4.20b
[37/107] tri_v2_089 (numeric) ... OK  n_active=28832  density=0.1202  topk20=0.000  ent=4.20b
[38/107] tri_v2_090 (binary) ... OK  n_active=19052  density=0.1135  topk20=0.042  ent=4.24b
[39/107] tri_v2_091 (binary) ... OK  n_active=18392  density=0.1169  topk20=0.077  ent=4.24b
[40/107] tri_v2_092 (binary) ... OK  n_active=17679  density=0.1174  topk20=0.036  ent=4.30b
[progress] 40/107 (37%) | success=100.0% | 0.013 prompts/s | ETA 85.4 min
[41/107] tri_v2_093 (binary) ... OK  n_active=21928  density=0.1203  topk20=0.000  ent=4.25b
[42/107] tri_v2_094 (binary) ... OK  n_active=29212  density=0.1172  topk20=0.000  ent=4.25b
[43/107] tri_v2_095 (binary) ... OK  n_active=27646  density=0.1153  topk20=0.000  ent=4.21b
[44/107] tri_v2_096 (binary) ... OK  n_active=23570  density=0.1179  topk20=0.012  ent=4.22b
[45/107] tri_v2_097 (binary) ... OK  n_active=23084  density=0.1251  topk20=0.029  ent=4.21b
[progress] 45/107 (42%) | success=100.0% | 0.013 prompts/s | ETA 78.7 min
[46/107] tri_v2_098 (binary) ... OK  n_active=21710  density=0.1206  topk20=0.012  ent=4.23b
[47/107] tri_v2_099 (binary) ... OK  n_active=25887  density=0.1217  topk20=0.001  ent=4.25b
[48/107] tri_v2_100 (binary) ... OK  n_active=18388  density=0.1311  topk20=0.082  ent=4.30b
[49/107] tri_v2_101 (binary) ... OK  n_active=19494  density=0.1162  topk20=0.072  ent=4.25b
[50/107] tri_v2_102 (binary) ... OK  n_active=17029  density=0.1287  topk20=0.085  ent=4.28b
[progress] 50/107 (47%) | success=100.0% | 0.013 prompts/s | ETA 71.7 min
[51/107] tri_v2_103 (binary) ... OK  n_active=28290  density=0.1173  topk20=0.000  ent=4.21b
[52/107] tri_v2_104 (numeric) ... OK  n_active=29219  density=0.1193  topk20=0.000  ent=4.20b
[53/107] tri_v2_105 (binary) ... OK  n_active=27261  density=0.1212  topk20=0.001  ent=4.26b
[54/107] tri_v2_106 (binary) ... OK  n_active=16463  density=0.1289  topk20=0.001  ent=4.28b
[55/107] tri_v2_107 (binary) ... OK  n_active=19242  density=0.1268  topk20=0.001  ent=4.30b
[progress] 55/107 (51%) | success=100.0% | 0.013 prompts/s | ETA 65.6 min
[56/107] tri_v2_108 (binary) ... OK  n_active=24710  density=0.1230  topk20=0.001  ent=4.23b
[57/107] tri_v2_109 (binary) ... OK  n_active=20989  density=0.1189  topk20=0.002  ent=4.26b
[58/107] tri_v2_110 (binary) ... OK  n_active=19439  density=0.1186  topk20=0.001  ent=4.27b
[59/107] tri_v2_111 (binary) ... OK  n_active=25306  density=0.1201  topk20=0.000  ent=4.24b
[60/107] tri_v2_112 (binary) ... OK  n_active=29187  density=0.1225  topk20=0.001  ent=4.22b
[progress] 60/107 (56%) | success=100.0% | 0.013 prompts/s | ETA 59.3 min
[61/107] tri_v2_113 (binary) ... OK  n_active=19851  density=0.1079  topk20=0.003  ent=4.28b
[62/107] tri_v2_114 (binary) ... OK  n_active=32343  density=0.1132  topk20=0.001  ent=4.19b
[63/107] tri_v2_115 (binary) ... OK  n_active=17059  density=0.1290  topk20=0.085  ent=4.29b
[64/107] tri_v2_116 (binary) ... OK  n_active=20063  density=0.1190  topk20=0.000  ent=4.26b
[65/107] tri_v2_117 (binary) ... OK  n_active=21928  density=0.1215  topk20=0.000  ent=4.25b
[progress] 65/107 (61%) | success=100.0% | 0.013 prompts/s | ETA 53.2 min
[66/107] tri_v2_118 (numeric) ... OK  n_active=28691  density=0.1170  topk20=0.000  ent=4.20b
[67/107] tri_v2_119 (binary) ... OK  n_active=18109  density=0.1261  topk20=0.004  ent=4.29b
[68/107] tri_v2_120 (binary) ... OK  n_active=21782  density=0.1190  topk20=0.009  ent=4.25b
[69/107] tri_v2_121 (binary) ... OK  n_active=21928  density=0.1215  topk20=0.000  ent=4.25b
[70/107] tri_v2_122 (binary) ... OK  n_active=27669  density=0.1220  topk20=0.001  ent=4.25b
[progress] 70/107 (65%) | success=100.0% | 0.013 prompts/s | ETA 47.1 min
[71/107] tri_v2_123 (binary) ... OK  n_active=16341  density=0.1286  topk20=0.001  ent=4.28b
[72/107] tri_v2_124 (binary) ... OK  n_active=29232  density=0.1216  topk20=0.000  ent=4.22b
[73/107] tri_v2_125 (binary) ... OK  n_active=27234  density=0.1200  topk20=0.001  ent=4.26b
[74/107] tri_v2_126 (binary) ... OK  n_active=19260  density=0.1187  topk20=0.002  ent=4.24b
[75/107] tri_v2_127 (binary) ... OK  n_active=18846  density=0.1165  topk20=0.069  ent=4.24b
[progress] 75/107 (70%) | success=100.0% | 0.013 prompts/s | ETA 40.9 min
[76/107] tri_v2_128 (binary) ... OK  n_active=20103  density=0.1251  topk20=0.001  ent=4.26b
[77/107] tri_v2_129 (binary) ... OK  n_active=22297  density=0.1252  topk20=0.027  ent=4.22b
[78/107] tri_v2_130 (binary) ... OK  n_active=20003  density=0.1116  topk20=0.026  ent=4.28b
[79/107] tri_v2_131 (binary) ... OK  n_active=16988  density=0.1289  topk20=0.089  ent=4.29b
[80/107] tri_v2_132 (binary) ... OK  n_active=30048  density=0.1169  topk20=0.000  ent=4.25b
[progress] 80/107 (75%) | success=100.0% | 0.013 prompts/s | ETA 34.4 min
[81/107] tri_v2_133 (binary) ... OK  n_active=24767  density=0.1227  topk20=0.001  ent=4.23b
[82/107] tri_v2_134 (binary) ... OK  n_active=16153  density=0.1298  topk20=0.001  ent=4.27b
[83/107] tri_v2_135 (binary) ... OK  n_active=15465  density=0.1238  topk20=0.017  ent=4.28b
[84/107] tri_v2_136 (binary) ... OK  n_active=27813  density=0.1162  topk20=0.000  ent=4.22b
[85/107] tri_v2_137 (binary) ... OK  n_active=24066  density=0.1174  topk20=0.012  ent=4.21b
[progress] 85/107 (79%) | success=100.0% | 0.013 prompts/s | ETA 28.0 min
[86/107] tri_v2_138 (binary) ... OK  n_active=16233  density=0.1302  topk20=0.001  ent=4.29b
[87/107] tri_v2_139 (binary) ... OK  n_active=22734  density=0.1164  topk20=0.011  ent=4.22b
[88/107] tri_v2_140 (binary) ... OK  n_active=18638  density=0.1283  topk20=0.001  ent=4.28b
[89/107] tri_v2_141 (binary) ... OK  n_active=30347  density=0.1148  topk20=0.001  ent=4.20b
[90/107] tri_v2_142 (numeric) ... OK  n_active=28523  density=0.1152  topk20=0.000  ent=4.20b
[progress] 90/107 (84%) | success=100.0% | 0.013 prompts/s | ETA 21.5 min
[91/107] tri_v2_143 (binary) ... OK  n_active=18302  density=0.1137  topk20=0.035  ent=4.23b
[92/107] tri_v2_144 (binary) ... OK  n_active=16630  density=0.1191  topk20=0.053  ent=4.29b
[93/107] tri_v2_145 (binary) ... OK  n_active=20719  density=0.1178  topk20=0.000  ent=4.25b
[94/107] tri_v2_146 (binary) ... OK  n_active=17788  density=0.1311  topk20=0.002  ent=4.29b
[95/107] tri_v2_147 (binary) ... OK  n_active=23087  density=0.1200  topk20=0.021  ent=4.22b
[progress] 95/107 (89%) | success=100.0% | 0.013 prompts/s | ETA 15.1 min
[96/107] tri_v2_148 (binary) ... OK  n_active=20532  density=0.1092  topk20=0.033  ent=4.27b
[97/107] tri_v2_149 (binary) ... OK  n_active=16535  density=0.1259  topk20=0.001  ent=4.27b
[98/107] tri_v2_150 (binary) ... OK  n_active=27631  density=0.1145  topk20=0.000  ent=4.21b
[99/107] tri_v2_151 (binary) ... OK  n_active=28523  density=0.1222  topk20=0.001  ent=4.23b
[100/107] tri_v2_152 (binary) ... OK  n_active=17602  density=0.1252  topk20=0.045  ent=4.28b
[progress] 100/107 (93%) | success=100.0% | 0.013 prompts/s | ETA 8.8 min
[101/107] tri_v2_153 (numeric) ... OK  n_active=29935  density=0.1170  topk20=0.000  ent=4.20b
[102/107] tri_v2_154 (binary) ... OK  n_active=18715  density=0.1267  topk20=0.004  ent=4.30b
[103/107] tri_v2_155 (numeric) ... OK  n_active=30589  density=0.1192  topk20=0.000  ent=4.21b
[104/107] tri_v2_156 (binary) ... OK  n_active=18519  density=0.1192  topk20=0.002  ent=4.30b
[105/107] tri_v2_157 (binary) ... OK  n_active=23526  density=0.1185  topk20=0.011  ent=4.21b
[progress] 105/107 (98%) | success=100.0% | 0.013 prompts/s | ETA 2.5 min
[106/107] tri_v2_158 (binary) ... OK  n_active=19268  density=0.1219  topk20=0.061  ent=4.26b
[107/107] tri_v2_159 (binary) ... OK  n_active=27677  density=0.1224  topk20=0.001  ent=4.25b
[progress] 107/107 (100%) | success=100.0% | 0.013 prompts/s | ETA 0.0 min

Done. Elapsed: 8031s
  Successes : 107
  Failures  : 0

## 6 — Summary and go/no-go check

In [8]:
from utils.graph_statistics import load_statistics, aggregate_statistics
import json

all_stats = load_statistics(STATS_FILE)
agg = aggregate_statistics(all_stats)

print(f"Total prompts in stats file : {agg['n_total']}")
print(f"Successfully attributed     : {agg['n_succeeded']}")
print(f"Success rate                : {agg['success_rate']:.1%}")
print()

# ── Legacy scalar block ────────────────────────────────────────────────────────
legacy_metrics = [
    'n_active_features', 'edge_density', 'mean_top50_score',
    'top10_over_top50', 'layer_entropy', 'mean_error_node_weight',
    'logit_gap',
]
print("── Legacy metrics ─────────────────────────────────────────────────────")
print(f"{'Metric':<32} {'Mean':>10} {'Std':>10} {'Median':>10} {'IQR':>10}")
print("-" * 76)
for m in legacy_metrics:
    v = agg.get(m)
    if v:
        print(f"{m:<32} {v['mean']:>10.4f} {v['std']:>10.4f} {v['median']:>10.4f} {v['iqr']:>10.4f}")
    else:
        print(f"{m:<32} {'N/A':>10}")

print()

# ── Supervisor layer_stats block ───────────────────────────────────────────────
print("── Supervisor: layer scalar summary ───────────────────────────────────")
print(f"{'Metric':<32} {'Mean':>10} {'Std':>10} {'Median':>10} {'IQR':>10}")
print("-" * 76)
for m in ['layer_stats_mean', 'layer_stats_std', 'layer_stats_median', 'layer_stats_entropy_bits']:
    v = agg.get(m)
    if v:
        print(f"{m:<32} {v['mean']:>10.4f} {v['std']:>10.4f} {v['median']:>10.4f} {v['iqr']:>10.4f}")
    else:
        print(f"{m:<32} {'N/A':>10}")

print()

# ── Supervisor topk20 scalars ──────────────────────────────────────────────────
print("── Supervisor: top-K=20 influence scalars ──────────────────────────────")
for m in ['topk20_score_total', 'topk20_score_gini']:
    v = agg.get(m)
    if v:
        print(f"{m:<32} mean={v['mean']:.4f}  std={v['std']:.4f}  IQR={v['iqr']:.4f}")
    else:
        print(f"{m:<32} N/A")

print()

# ── Supervisor: prune_curve summary (mean node/edge counts per threshold) ──────
pc = agg.get("prune_curve_agg")
if pc:
    print("── Supervisor: prune curve (mean across prompts) ───────────────────────")
    print(f"{'Threshold':>10} {'Mean nodes':>12} {'Mean edges':>12} {'Mean density':>14}")
    print("-" * 52)
    for t_str, vals in sorted(pc.items(), key=lambda x: float(x[0])):
        mn = vals["mean_n_nodes"]
        me = vals["mean_n_edges"]
        md = vals["mean_density"]
        print(
            f"{float(t_str):>10.2f} "
            f"{mn if mn is None else f'{mn:>12.1f}'} "
            f"{me if me is None else f'{me:>12.1f}'} "
            f"{md if md is None else f'{md:>14.6f}'}"
        )
    print()

# ── Go/no-go check ─────────────────────────────────────────────────────────────
sr = agg['success_rate']
if sr < 0.70:
    print("STOP: Success rate below 70%. Investigate prompt set before proceeding.")
elif sr < 0.85:
    print(f"NOTE: Success rate {sr:.1%} is below 85%. Proceed but flag as limitation.")
else:
    print(f"Success rate {sr:.1%} — OK to proceed to notebook 03.")

Total prompts in stats file : 159
Successfully attributed     : 159
Success rate                : 100.0%

── Legacy metrics ─────────────────────────────────────────────────────
Metric                                 Mean        Std     Median        IQR
----------------------------------------------------------------------------
n_active_features                22987.6478  4938.5657 22180.0000  9094.0000
edge_density                         0.1205     0.0051     0.1200     0.0070
mean_top50_score                     0.0004     0.0007     0.0000     0.0006
top10_over_top50                     0.4168     0.0740     0.3852     0.1089
layer_entropy                        2.3348     0.2404     2.3320     0.3458
mean_error_node_weight               0.3065     0.0356     0.2938     0.0252
logit_gap                           -0.2101     2.9803     0.9960     2.5605

── Supervisor: layer scalar summary ───────────────────────────────────
Metric                                 Mean        Std     Median        IQR
----------------------------------------------------------------------------
layer_stats_mean                     8.8108     0.2617     8.8165     0.4812
layer_stats_std                      7.1821     0.0984     7.1792     0.1702
layer_stats_median                   6.9371     0.2428     7.0000     0.0000
layer_stats_entropy_bits             4.2461     0.0315     4.2479     0.0566

── Supervisor: top-K=20 influence scalars ──────────────────────────────
topk20_score_total               mean=0.0154  std=0.0254  IQR=0.0215
topk20_score_gini                mean=0.2496  std=0.0685  IQR=0.1041

── Supervisor: prune curve (mean across prompts) ───────────────────────
 Threshold   Mean nodes   Mean edges   Mean density
----------------------------------------------------
      0.50        361.6      20752.6       0.154990
      0.60        787.7      96747.0       0.153930
      0.70       1508.3     355294.7       0.155070
      0.80       2719.1    1143754.3       0.154175
      0.90       4793.2    3491692.1       0.151756
      0.95       6404.4    6055004.9       0.147482
      0.99       8189.4    9507423.6       0.141709

Success rate 100.0% — OK to proceed to notebook 03.

## 6 — Scale-up decision

After the pilot: if **`n_success >= N_PILOT * 0.9`** (or whenever you want the full probe set),

set **`RUN_FULL = True`** in §1 and **re-run from §1**.

§5 skips IDs already recorded in **`stats_lora_combined.json`** (if any) **and**

**reuses pilot successes by copying rows** — no duplicate attribution cost for prompts that finished during the pilot.